второе задание
Papai145/dz-JS pull request #2
Opened 2024-06-12 07:16 UTC by Papai145

2024-06-14 09:18 UTC, GitEsense requested changes
Необходимо поправить функцию Crypto

2024-06-14 09:18 UTC, GitEsense commented on 8-crypto/app.js
> +console.log(check("wordssap"));
Функции реализованы неверно.
1. Функция `crypto` должна быть обратима (пример ниже)
```js
const pwd = 'password'
const encrypt = crypto(pwd) // ssapdorw
const decrypt = crypto(encrypt) // password
```
2. Функция `check` не проводить никаких манипуляций, мы должны использовать обратимость функции крипто (см. п.1.) и тем самым вызов будет возвращать true или false
```js
function checkPassword(encryptedPassword, originalPassword) {
    if (!encryptedPassword || !originalPassword) {
        return false;
    }
    return originalPassword === crypt(encryptedPassword);
}
```

2024-06-14 09:18 UTC, GitEsense commented on 9-sort-loops/app.js
> +        result[i + 1] = temp;
Тут можно воспользоваться трюком обмена переменными
https://learn.javascript.ru/destructuring-assignment

2024-06-14 09:18 UTC, GitEsense commented on 9-sort-loops/app.js
> +console.log(sorting(arr));
```js
const numbers = Array.from({ length: 1000 }, () => {
    const max = 1000000;
    const min = 1000;
    const factor = Math.random() > 0.5 ? 1 : -1;
    const randomNumber = Math.ceil(Math.random() * (max - min)) + min;
    return randomNumber * factor;
});

function orderTemplate(firstNumber, secondNumber, desc) {
    if (!desc) {
        return firstNumber > secondNumber;
    }
    return firstNumber < secondNumber;
}

function sortArray(incomingArray, desc = false) {
    const array = [...incomingArray];
    for (let i = 0; i < array.length; i++) {
        for (let j = i; j < array.length; j++) {
            const isExchange = orderTemplate(array[i], array[j], desc);
            if (isExchange) {
                [array[i], array[j]] = [array[j], array[i]];
            }
        }
    }
    return array;
}

console.log(numbers);
console.log('Отсортированный по возрастанию массив:', sortArray(numbers));
console.log('Отсортированный по убыванию массив:', sortArray(numbers, true));

```

2024-06-14 09:18 UTC, GitEsense commented on 9-sort-loops/app.js
> +    for (let i = 0; i < result.length - 1; i++) {
Можно сократить кол-во итераций за счёт приравнивания i к j (хотя именовать надо наоборот, i - j - k ...)

`for (let i = j + 1; i < result.length; i++)`

2024-06-15 04:36 UTC, Papai145 commented on 7-convector/app.js
> +};
исправил

2024-06-15 06:01 UTC, Papai145 commented on 8-crypto/app.js
> +console.log(check("wordssap"));
принято

2024-06-15 06:06 UTC, Papai145 commented on 9-sort-loops/app.js
> +        result[i + 1] = temp;
принято

2024-06-15 07:17 UTC, Papai145 commented on 9-sort-loops/app.js
> +    for (let i = 0; i < result.length - 1; i++) {
не совсем понимаю как это уменьшит количество итерации

2024-06-15 08:27 UTC, Papai145 commented on 9-sort-loops/app.js
> +console.log(sorting(arr));
с выносом логики в функцию   orderTemplate я понял.Только вопрос:как определить когда выносить логику в отдельную функцию а когда не надо

2024-06-15 09:24 UTC, GitEsense commented on 9-sort-loops/app.js
> +    for (let i = 0; i < result.length - 1; i++) {
> не совсем понимаю как это уменьшит количество итерации

Мы не будем проходить по уже пройденным числам, так не будем сравнивать с самим собой 
Можете на выполнение функции поставить переменную count и на каждом проходе вложенного цикла увеличивать на 1 и при завершении вывести в консоль, Вы увидите кол-во итераций и разницу

2024-06-15 09:25 UTC, GitEsense commented on 9-sort-loops/app.js
> +console.log(sorting(arr));
> с выносом логики в функцию orderTemplate я понял.Только вопрос:как определить когда выносить логику в отдельную функцию а когда не надо

Если это надо где-то переиспользовать (т.е. один и тот же функционал требуется в нескольких местах), то можно вынести, если нет - можно использовать просто единоразово внутри функции

2024-06-17 09:02 UTC, GitEsense approved these changes
Вот теперь отлично.
Пример функции "Криптографии"
```js
function crypt(password) {
    if (!password || !password.length) {
        return NaN;
    }
    const splitedArray = password.split('');
    if (splitedArray.length < 8) {
        return false;
    }

    const middleIndex = Math.floor(splitedArray.length / 2);
    const firstHalf = splitedArray.slice(0, middleIndex).reverse();
    const secondHalf = splitedArray.slice(middleIndex).reverse();
    const length = secondHalf.length;
    [secondHalf[1], secondHalf[length - 2]] = [secondHalf[length - 2], secondHalf[1]];

    const encryptedPassword = firstHalf.concat(secondHalf);
    return encryptedPassword.join('');
}

function checkPassword(encryptedPassword, originalPassword) {
    if (!encryptedPassword || !originalPassword) {
        return false;
    }
    return originalPassword === crypt(encryptedPassword);
}

function getRandomNumber(min = 0, max = 86) {
    return Math.ceil(Math.random() * (max - min)) + min;
}

function getRandomPassword(length = 12) {
    const symbolArray = Array.from({ length: 87 }, (_, index) => String.fromCharCode(index + 33));
    console.log(symbolArray);
    const password = Array.from({ length }, () => symbolArray[getRandomNumber()]);
    return password.join('');
}

/*
    logging and test function with console
*/

const password = getRandomPassword();
const encrypted = crypt(password);

console.log('Пароль:', password);
console.log('Зашифрованный пароль:', encrypted);
console.log('Проверка пароля:', checkPassword(encrypted, password));

const password2 = getRandomPassword();
const encrypted2 = crypt(password2).substring(1);

console.log('Пароль:', password2);
console.log('Зашифрованный пароль:', encrypted2);
console.log('Проверка пароля:', checkPassword(encrypted2, getRandomPassword()));

```

За пример взято условие, предложенное в задании, мы делим пароль пополам и уже с ним работаем, т.к. символов может быть и 10 и 20, поэтому резать "на 4" и остальные не совсем разумно

2024-06-17 15:14 UTC, merged