задания № 16,17
Papai145/dz-JS pull request #5
Opened 2024-06-30 12:33 UTC by Papai145

2024-07-01 07:43 UTC, GitEsense requested changes
Давайте внесём некоторые корректировки

2024-07-01 07:43 UTC, GitEsense commented on 16-another_tasks/app.js
> +updatedDesc(4, "сделать только английский !!!!");
Вы верно применяете bind (можно так же использовать call или apply - в зависимости от потребностей), однако, неверно используете.
у Нас логика работы должна быть следующая:
1. Создаём новый объект (newTask) с параметром (tasks = [], можно без параметра, но в логику тогда необходимо добавлять проверку на наличие \ отсутствие свойства и если его нет - добавлять)
2. Вызываем метод toDoList (без преобразований и изменений) с привязкой контекста
3. Проверяем вывод - результатом будет "добавление \ изменение \ удаление \ сортировка" задач в новом объекте (newTask)

Чтобы передать дополнительные параметры как я и говорил в предыдущем ревью - хорошо бы работать именно с объектом и его обновлять, добавляя параметры, если появились "новые"

2024-07-01 07:43 UTC, GitEsense commented on 17-calc/index.html
> +        />
Давайте сделаем всплытие события, т.к. в данном случае мы передаём онкликом конкретную функцию, а что если  таких инпутов будет 10? 100? 1000 ?

2024-07-01 07:43 UTC, GitEsense commented on 17-calc/index.html
> +      </div>
Тоже самое - можно реализовать через всплытие, тем самым перехватывая событие и проводя какие-то операции по событию

2024-07-01 07:43 UTC, GitEsense commented on 17-calc/app.js
> +  let number2 = Number(page.numbers[1].value);
Заметил, что Вы не любите использовать деструктуризацию и рест операторы, тут можно было бы оформить как
```js
const [num1, num2] = [...page.numbers].map(({ value }) => Number(value));

а в логику проверки делать от обратного, мы проверяем не "если истина", а сначала с "негативного"
    if (isNaN(num1) || isNaN(num2)) {
        page.information.innerText = `Не корректные данные `;
        return;
    }
```
затем сделать switch case или объект, т.к. в данном случае у нас есть 4 действия и 4 "ключа", то расширять удобнее будет именно объектом, сделать что-то вроде

```js
    const action = {
        1: (a, b) => a + b,
        2: (a, b) => a - b,
        3: (a, b) => a * b,
        4: (a, b) => (b === 0 ? 'нельзя делить на 0' : a / b),
    };

    const { name } = e.target;
    const result = action[name](num1, num2);

    show(result);
```

2024-07-01 07:43 UTC, GitEsense commented on 17-calc/app.js
> +}
```js
function show(result) {
    page.information.innerText = `Результат = ${isNaN(result) ? result : result.toFixed(2)}`;
    [...page.numbers].map((x) => (x.value = ''));
}
```

2024-07-01 17:23 UTC, Papai145 commented on 16-another_tasks/app.js
> +updatedDesc(4, "сделать только английский !!!!");
как быть с моим методом проверки checkElement()? Вижу только один выход:в старом объекте интегрировать проверку в каждый метод

2024-07-03 07:58 UTC, GitEsense approved these changes
Ну, всё отлично!)

2024-07-03 07:58 UTC, GitEsense commented on 16-another_tasks/app.js
> +newTasksUpdateFu(4, "сделать уроки обязательно");
Вот тут Мы обращаемся к функции обновления, вопросов нет, только вот хорошо бы всё-таки передавать объект, а не строку, тогда мы сможем добавить несколько параметров, например добавить description и date, в остальном всё ок
можно было ещё использовать не bind (создание новой функции), а вызывать функцию с переданным контекстом через call/apply

2024-07-04 15:05 UTC, merged